In [1]:
from tools.tokenizer import *
from tools.datasets import *
from tools.models import *
from tqdm import tqdm 

c:\Users\gabri\anaconda3\envs\nlp_dl\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [5]:
dataset_train, dataset_test, tokenizer = get_dataset_fake()
train_loader = DataLoader(dataset_train, 
                          batch_size=1, 
                          shuffle=True)

In [7]:
# Load torch model

loaded_model = MyRegressor(tokenizer.vocab_size, 128, 128, 1)
loaded_model.load_state_dict(torch.load('./saved_models/model.pth'))

reds = [train_loader.dataset[i][0] for i in range(10)]
y_true = [train_loader.dataset[i][1] for i in range(10)]
y_pred = [loaded_model(x.reshape(1, -1).to('cpu')).item() for x in reds]

y_pred, y_true

C:\Users\gabri\AppData\Local\Temp\ipykernel_24916\1939170610.py:4: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  loaded_model.load_state_dict(torch.load('./saved_models/mode

([975.12939453125,
  705.8336791992188,
  734.2213134765625,
  780.4610595703125,
  588.8346557617188,
  1110.27197265625,
  1241.2952880859375,
  896.0108032226562,
  795.94873046875,
  524.540283203125],
 [tensor([800]),
  tensor([900]),
  tensor([800]),
  tensor([650]),
  tensor([850]),
  tensor([920]),
  tensor([800]),
  tensor([800]),
  tensor([1000]),
  tensor([800])])

In [18]:
redacao_exemplo = """
Tema: Impacto da tecnologia na educação: desafios e oportunidades

Redação: A tecnologia tem se tornado uma aliada indispensável no campo educacional, oferecendo inúmeras oportunidades de inovação e acesso ao conhecimento. No entanto, a implementação de recursos tecnológicos nas escolas brasileiras enfrenta desafios significativos, como a desigualdade no acesso à internet e a falta de capacitação dos professores. A pandemia de COVID-19 evidenciou a importância da tecnologia na educação, mas também expôs a vulnerabilidade de muitos alunos que não possuem os meios necessários para acompanhar o ensino remoto. Além disso, a formação inadequada dos educadores para utilizar ferramentas digitais limita o potencial transformador da tecnologia. Portanto, é essencial que políticas públicas sejam desenvolvidas para garantir a infraestrutura tecnológica adequada e a formação contínua dos professores, a fim de democratizar o acesso ao ensino de qualidade e preparar os estudantes para um futuro cada vez mais digital.

"""

nota_exemplo = 800

In [19]:
torch.tensor([tokenizer(redacao_exemplo)])

tensor([[1266,  134,  561, 1111, 1199, 1728, 1980, 1920,   51,   17,  101, 1111,
         1362, 1756, 1016,  795,  784, 1579, 1429, 1228,  885,  793, 2092,   51,
          247,   55, 1920, 1313, 2108,  169, 1429, 1131,  101, 1632,  247, 1196,
          668,  414,  746,  365, 1832, 1980,   40, 2070,  101, 1463, 1429, 1313,
          364,  333, 1920,  101, 1976,  247,  764,  637, 2244,  101, 1449,  247,
         1194, 2008,  930,  101,  321,  561, 1111, 1199, 1728, 1771,  382, 1786,
          101, 1690,  247, 1195, 1315,  860, 1119, 1363, 1672,  285, 1961,  735,
         1567, 1085,  769, 1930,  231, 2090,  101,  363,  539,  637, 1863,  735,
         1261, 2049,  244,  857, 1085, 1094, 2147,  561, 1111, 1869,  814,  770,
          860, 1848,  940,  712, 2031,  735, 1383,  101, 2214, 1556,  535, 1920,
          101,  363,  819,  637, 2244,  101, 1816,  247]])

In [20]:
redacao_tokenizada = torch.tensor([tokenizer(redacao_exemplo)])

In [21]:
loaded_model(redacao_tokenizada)

tensor([[[736.2334]]], grad_fn=<ViewBackward0>)