In [1]:
from tools.tokenizer import *
from tools.datasets import *
from tools.models import *
from tqdm import tqdm 

c:\Users\gabri\anaconda3\envs\nlp_dl\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
# model = MyRegressor(tokenizer.vocab_size, 128, 128, 1)
# print(model(train_loader.dataset[0][0].reshape(1, -1)))
# print(train_loader.dataset[0][0].reshape(1, -1))

# for x in train_loader:
#     print(x[0])
#     print(model(x[0]))
#     break

In [6]:
dataset_train, dataset_test, tokenizer = get_dataset_fake()

n_epochs = 50
batch_size = 1
device = 'cpu'
sentence_length = 128
sample_size = 1.0

model = MyRegressor(tokenizer.vocab_size, 128, 128, 1)
model.to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=0.1)
criterion = nn.MSELoss()

train_loader = DataLoader(dataset_train, 
                          batch_size=batch_size, 
                          shuffle=True)

history = []

for epoch in range(n_epochs):
    epoch_loss = 0
    batch_loss = 0
    
    print(f"Epoch {epoch+1}/{n_epochs}")
    
    # Barra de progresso customizada para o Keras-like TQDM
    progress_bar = tqdm(enumerate(train_loader), 
                        total=len(train_loader), 
                        # desc=f"Epoch {epoch+1}/{n_epochs}", 
                        leave=True)
    
    for i, batch in progress_bar:
        X, y = batch
        X = X.to(device)
        y = y.to(device)
        optimizer.zero_grad()
        output = model(X)
        loss = criterion(output, y.float())
        loss.backward()
        optimizer.step()
        
        batch_loss = loss.item()
        epoch_loss += batch_loss
        progress_bar.set_postfix({"batch_loss": batch_loss})
        
    epoch_loss /= len(train_loader)
    
    history.append(epoch_loss)
    tqdm.write(f"Epoch {epoch}/{n_epochs} - loss: {epoch_loss:.4f}")

    print("\n")

Epoch 1/50


  0%|          | 0/106 [00:00<?, ?it/s]c:\Users\gabri\anaconda3\envs\nlp_dl\lib\site-packages\torch\nn\modules\loss.py:538: UserWarning: Using a target size (torch.Size([1, 1])) that is different to the input size (torch.Size([1, 1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
  0%|          | 0/106 [00:00<?, ?it/s, batch_loss=9.94e+5]

100%|██████████| 106/106 [00:01<00:00, 102.29it/s, batch_loss=1.66e+5]


Epoch 0/50 - loss: 307584.4847


Epoch 2/50


100%|██████████| 106/106 [00:01<00:00, 92.23it/s, batch_loss=4.31e+4]


Epoch 1/50 - loss: 29206.9913


Epoch 3/50


100%|██████████| 106/106 [00:01<00:00, 87.62it/s, batch_loss=68.5]   


Epoch 2/50 - loss: 22888.3760


Epoch 4/50


100%|██████████| 106/106 [00:01<00:00, 93.88it/s, batch_loss=115]    


Epoch 3/50 - loss: 34827.9028


Epoch 5/50


100%|██████████| 106/106 [00:00<00:00, 113.30it/s, batch_loss=2.02e+4]


Epoch 4/50 - loss: 28465.2245


Epoch 6/50


100%|██████████| 106/106 [00:00<00:00, 115.06it/s, batch_loss=1.43e+4]


Epoch 5/50 - loss: 27656.9887


Epoch 7/50


100%|██████████| 106/106 [00:01<00:00, 102.41it/s, batch_loss=1.66e+3]


Epoch 6/50 - loss: 22198.4892


Epoch 8/50


100%|██████████| 106/106 [00:00<00:00, 138.49it/s, batch_loss=5.26e+3]


Epoch 7/50 - loss: 21078.5349


Epoch 9/50


100%|██████████| 106/106 [00:00<00:00, 118.58it/s, batch_loss=2.03e+4]


Epoch 8/50 - loss: 21155.9604


Epoch 10/50


100%|██████████| 106/106 [00:01<00:00, 97.84it/s, batch_loss=130]    


Epoch 9/50 - loss: 16282.8001


Epoch 11/50


100%|██████████| 106/106 [00:00<00:00, 115.08it/s, batch_loss=5.92e+3]


Epoch 10/50 - loss: 16229.1593


Epoch 12/50


100%|██████████| 106/106 [00:01<00:00, 101.21it/s, batch_loss=331]   


Epoch 11/50 - loss: 16021.1562


Epoch 13/50


100%|██████████| 106/106 [00:00<00:00, 106.65it/s, batch_loss=1.38e+3]


Epoch 12/50 - loss: 13785.9799


Epoch 14/50


100%|██████████| 106/106 [00:00<00:00, 115.11it/s, batch_loss=8.71e+3]


Epoch 13/50 - loss: 13094.5396


Epoch 15/50


100%|██████████| 106/106 [00:01<00:00, 98.04it/s, batch_loss=3.26e+4]


Epoch 14/50 - loss: 13810.5227


Epoch 16/50


100%|██████████| 106/106 [00:00<00:00, 116.49it/s, batch_loss=6.33e+3]


Epoch 15/50 - loss: 15349.0468


Epoch 17/50


100%|██████████| 106/106 [00:00<00:00, 124.01it/s, batch_loss=2.87e+3]


Epoch 16/50 - loss: 15178.0855


Epoch 18/50


100%|██████████| 106/106 [00:01<00:00, 100.73it/s, batch_loss=7.4e+3]


Epoch 17/50 - loss: 13665.5359


Epoch 19/50


100%|██████████| 106/106 [00:00<00:00, 125.25it/s, batch_loss=5.41e+3]


Epoch 18/50 - loss: 14390.5496


Epoch 20/50


100%|██████████| 106/106 [00:00<00:00, 122.25it/s, batch_loss=5.18e+3]


Epoch 19/50 - loss: 13039.3851


Epoch 21/50


100%|██████████| 106/106 [00:01<00:00, 100.73it/s, batch_loss=3.03e+4]


Epoch 20/50 - loss: 14481.3349


Epoch 22/50


100%|██████████| 106/106 [00:00<00:00, 128.98it/s, batch_loss=680]   


Epoch 21/50 - loss: 22271.6613


Epoch 23/50


100%|██████████| 106/106 [00:00<00:00, 128.96it/s, batch_loss=4.08e+4]


Epoch 22/50 - loss: 22758.8206


Epoch 24/50


100%|██████████| 106/106 [00:01<00:00, 101.12it/s, batch_loss=1.12e+4]


Epoch 23/50 - loss: 20037.0184


Epoch 25/50


100%|██████████| 106/106 [00:00<00:00, 110.91it/s, batch_loss=5.5e+3]


Epoch 24/50 - loss: 24483.7194


Epoch 26/50


100%|██████████| 106/106 [00:00<00:00, 121.46it/s, batch_loss=1.77e+4]


Epoch 25/50 - loss: 23386.6606


Epoch 27/50


100%|██████████| 106/106 [00:01<00:00, 105.86it/s, batch_loss=1.4e+4] 


Epoch 26/50 - loss: 26221.9523


Epoch 28/50


100%|██████████| 106/106 [00:00<00:00, 110.55it/s, batch_loss=6.83e+3]


Epoch 27/50 - loss: 23425.9914


Epoch 29/50


100%|██████████| 106/106 [00:00<00:00, 119.05it/s, batch_loss=2.57e+3]


Epoch 28/50 - loss: 22186.2532


Epoch 30/50


100%|██████████| 106/106 [00:00<00:00, 112.94it/s, batch_loss=6.38e+4]


Epoch 29/50 - loss: 17968.1530


Epoch 31/50


100%|██████████| 106/106 [00:00<00:00, 121.56it/s, batch_loss=1.38e+4]


Epoch 30/50 - loss: 22128.7655


Epoch 32/50


100%|██████████| 106/106 [00:00<00:00, 118.15it/s, batch_loss=3.74e+4]


Epoch 31/50 - loss: 16189.5255


Epoch 33/50


100%|██████████| 106/106 [00:00<00:00, 108.28it/s, batch_loss=43]    


Epoch 32/50 - loss: 17331.1791


Epoch 34/50


100%|██████████| 106/106 [00:00<00:00, 128.87it/s, batch_loss=1.37e+3]


Epoch 33/50 - loss: 14499.3263


Epoch 35/50


100%|██████████| 106/106 [00:01<00:00, 92.80it/s, batch_loss=4.87e+4]


Epoch 34/50 - loss: 13969.3781


Epoch 36/50


100%|██████████| 106/106 [00:00<00:00, 114.05it/s, batch_loss=299]    


Epoch 35/50 - loss: 18783.7169


Epoch 37/50


100%|██████████| 106/106 [00:00<00:00, 127.33it/s, batch_loss=2.5e+3]


Epoch 36/50 - loss: 15186.9979


Epoch 38/50


100%|██████████| 106/106 [00:01<00:00, 98.54it/s, batch_loss=7.28e+3] 


Epoch 37/50 - loss: 19430.3820


Epoch 39/50


100%|██████████| 106/106 [00:00<00:00, 129.43it/s, batch_loss=3.26e+3]


Epoch 38/50 - loss: 18218.0027


Epoch 40/50


100%|██████████| 106/106 [00:00<00:00, 136.71it/s, batch_loss=3.31e+4]


Epoch 39/50 - loss: 17112.1035


Epoch 41/50


100%|██████████| 106/106 [00:00<00:00, 108.68it/s, batch_loss=2.15e+4]


Epoch 40/50 - loss: 16780.5836


Epoch 42/50


100%|██████████| 106/106 [00:00<00:00, 128.66it/s, batch_loss=1.01e+4]


Epoch 41/50 - loss: 18699.4221


Epoch 43/50


100%|██████████| 106/106 [00:00<00:00, 139.34it/s, batch_loss=6.87e+3]


Epoch 42/50 - loss: 18038.4180


Epoch 44/50


100%|██████████| 106/106 [00:00<00:00, 116.90it/s, batch_loss=123]    


Epoch 43/50 - loss: 16968.1085


Epoch 45/50


100%|██████████| 106/106 [00:00<00:00, 118.28it/s, batch_loss=8.62e+4]


Epoch 44/50 - loss: 18905.5034


Epoch 46/50


100%|██████████| 106/106 [00:00<00:00, 139.97it/s, batch_loss=227]    


Epoch 45/50 - loss: 17195.0730


Epoch 47/50


100%|██████████| 106/106 [00:00<00:00, 129.39it/s, batch_loss=1.36e+3]


Epoch 46/50 - loss: 18216.5049


Epoch 48/50


100%|██████████| 106/106 [00:00<00:00, 111.10it/s, batch_loss=6.86e+4]


Epoch 47/50 - loss: 18759.8271


Epoch 49/50


100%|██████████| 106/106 [00:00<00:00, 139.19it/s, batch_loss=6.92e+4]


Epoch 48/50 - loss: 22320.2238


Epoch 50/50


100%|██████████| 106/106 [00:00<00:00, 132.87it/s, batch_loss=727]   

Epoch 49/50 - loss: 24952.6045




In [18]:
reds = [train_loader.dataset[i][0] for i in range(10)]
y_true = [train_loader.dataset[i][1] for i in range(10)]
y_pred = [model(x.reshape(1, -1).to(device)).item() for x in reds]

In [20]:
y_pred, y_true

([790.3740234375,
  778.5909423828125,
  827.7506713867188,
  713.5306396484375,
  751.2713623046875,
  959.2432861328125,
  681.5054321289062,
  733.6400146484375,
  771.7236938476562,
  952.1657104492188],
 [tensor([800]),
  tensor([900]),
  tensor([800]),
  tensor([650]),
  tensor([850]),
  tensor([920]),
  tensor([800]),
  tensor([800]),
  tensor([1000]),
  tensor([800])])

In [22]:
# saving torch model

torch.save(model.state_dict(), './saved_models/model.pth')

In [24]:
# Load torch model

loaded_model = MyRegressor(tokenizer.vocab_size, 128, 128, 1)
loaded_model.load_state_dict(torch.load('./saved_models/model.pth'))

reds = [train_loader.dataset[i][0] for i in range(10)]
y_true = [train_loader.dataset[i][1] for i in range(10)]
y_pred = [loaded_model(x.reshape(1, -1).to(device)).item() for x in reds]

y_pred, y_true

C:\Users\gabri\AppData\Local\Temp\ipykernel_39524\1140413588.py:4: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  loaded_model.load_state_dict(torch.load('./saved_models/mode

([790.3740234375,
  778.5909423828125,
  827.7506713867188,
  713.5306396484375,
  751.2713623046875,
  959.2432861328125,
  681.5054321289062,
  733.6400146484375,
  771.7236938476562,
  952.1657104492188],
 [tensor([800]),
  tensor([900]),
  tensor([800]),
  tensor([650]),
  tensor([850]),
  tensor([920]),
  tensor([800]),
  tensor([800]),
  tensor([1000]),
  tensor([800])])